// Code generated by MockGen. DO NOT EDIT.
// Source: ../cache/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../cache/interfaces.go -destination=../mocks/cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	generator "orders/internal/generator"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersCache is a mock of OrdersCache interface.
type MockOrdersCache struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersCacheMockRecorder
	isgomock struct{}
}

// MockOrdersCacheMockRecorder is the mock recorder for MockOrdersCache.
type MockOrdersCacheMockRecorder struct {
	mock *MockOrdersCache
}

// NewMockOrdersCache creates a new mock instance.
func NewMockOrdersCache(ctrl *gomock.Controller) *MockOrdersCache {
	mock := &MockOrdersCache{ctrl: ctrl}
	mock.recorder = &MockOrdersCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersCache) EXPECT() *MockOrdersCacheMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockOrdersCache) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockOrdersCacheMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOrdersCache)(nil).Close))
}

// GetFromCache mocks base method.
func (m *MockOrdersCache) GetFromCache(ctx context.Context, uid string) (*generator.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromCache", ctx, uid)
	ret0, _ := ret[0].(*generator.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromCache indicates an expected call of GetFromCache.
func (mr *MockOrdersCacheMockRecorder) GetFromCache(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromCache", reflect.TypeOf((*MockOrdersCache)(nil).GetFromCache), ctx, uid)
}

// LoadInitialOrders mocks base method.
func (m *MockOrdersCache) LoadInitialOrders(ctx context.Context, latestOrders []*generator.Order, limit int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LoadInitialOrders", ctx, latestOrders, limit)
}

// LoadInitialOrders indicates an expected call of LoadInitialOrders.
func (mr *MockOrdersCacheMockRecorder) LoadInitialOrders(ctx, latestOrders, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadInitialOrders", reflect.TypeOf((*MockOrdersCache)(nil).LoadInitialOrders), ctx, latestOrders, limit)
}

// UpdateCache mocks base method.
func (m *MockOrdersCache) UpdateCache(ctx context.Context, order *generator.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCache", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCache indicates an expected call of UpdateCache.
func (mr *MockOrdersCacheMockRecorder) UpdateCache(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCache", reflect.TypeOf((*MockOrdersCache)(nil).UpdateCache), ctx, order)
}
