// Code generated by MockGen. DO NOT EDIT.
// Source: ../kafka/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../kafka/interfaces.go -destination=../mocks/kafka_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kafka "github.com/segmentio/kafka-go"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesConsumer is a mock of MessagesConsumer interface.
type MockMessagesConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesConsumerMockRecorder
	isgomock struct{}
}

// MockMessagesConsumerMockRecorder is the mock recorder for MockMessagesConsumer.
type MockMessagesConsumerMockRecorder struct {
	mock *MockMessagesConsumer
}

// NewMockMessagesConsumer creates a new mock instance.
func NewMockMessagesConsumer(ctrl *gomock.Controller) *MockMessagesConsumer {
	mock := &MockMessagesConsumer{ctrl: ctrl}
	mock.recorder = &MockMessagesConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesConsumer) EXPECT() *MockMessagesConsumerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessagesConsumer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessagesConsumerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessagesConsumer)(nil).Close))
}

// CommitMessages mocks base method.
func (m *MockMessagesConsumer) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitMessages indicates an expected call of CommitMessages.
func (mr *MockMessagesConsumerMockRecorder) CommitMessages(ctx any, msgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitMessages", reflect.TypeOf((*MockMessagesConsumer)(nil).CommitMessages), varargs...)
}

// FetchMessage mocks base method.
func (m *MockMessagesConsumer) FetchMessage(ctx context.Context) (kafka.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMessage", ctx)
	ret0, _ := ret[0].(kafka.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMessage indicates an expected call of FetchMessage.
func (mr *MockMessagesConsumerMockRecorder) FetchMessage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMessage", reflect.TypeOf((*MockMessagesConsumer)(nil).FetchMessage), ctx)
}

// MockMessagesProducer is a mock of MessagesProducer interface.
type MockMessagesProducer struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesProducerMockRecorder
	isgomock struct{}
}

// MockMessagesProducerMockRecorder is the mock recorder for MockMessagesProducer.
type MockMessagesProducerMockRecorder struct {
	mock *MockMessagesProducer
}

// NewMockMessagesProducer creates a new mock instance.
func NewMockMessagesProducer(ctrl *gomock.Controller) *MockMessagesProducer {
	mock := &MockMessagesProducer{ctrl: ctrl}
	mock.recorder = &MockMessagesProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesProducer) EXPECT() *MockMessagesProducerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessagesProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessagesProducerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessagesProducer)(nil).Close))
}

// WriteMessages mocks base method.
func (m *MockMessagesProducer) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range msgs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteMessages", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessages indicates an expected call of WriteMessages.
func (mr *MockMessagesProducerMockRecorder) WriteMessages(ctx any, msgs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, msgs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessages", reflect.TypeOf((*MockMessagesProducer)(nil).WriteMessages), varargs...)
}
