// Code generated by MockGen. DO NOT EDIT.
// Source: ../repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../repository/interfaces.go -destination=../mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	generator "orders/internal/generator"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersRepository is a mock of OrdersRepository interface.
type MockOrdersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersRepositoryMockRecorder
	isgomock struct{}
}

// MockOrdersRepositoryMockRecorder is the mock recorder for MockOrdersRepository.
type MockOrdersRepositoryMockRecorder struct {
	mock *MockOrdersRepository
}

// NewMockOrdersRepository creates a new mock instance.
func NewMockOrdersRepository(ctrl *gomock.Controller) *MockOrdersRepository {
	mock := &MockOrdersRepository{ctrl: ctrl}
	mock.recorder = &MockOrdersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersRepository) EXPECT() *MockOrdersRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockOrdersRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockOrdersRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOrdersRepository)(nil).Close))
}

// GetAllOrders mocks base method.
func (m *MockOrdersRepository) GetAllOrders(ctx context.Context) ([]*generator.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", ctx)
	ret0, _ := ret[0].([]*generator.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrdersRepositoryMockRecorder) GetAllOrders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrdersRepository)(nil).GetAllOrders), ctx)
}

// GetLatestOrders mocks base method.
func (m *MockOrdersRepository) GetLatestOrders(ctx context.Context, limit int32) ([]*generator.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestOrders", ctx, limit)
	ret0, _ := ret[0].([]*generator.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestOrders indicates an expected call of GetLatestOrders.
func (mr *MockOrdersRepositoryMockRecorder) GetLatestOrders(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestOrders", reflect.TypeOf((*MockOrdersRepository)(nil).GetLatestOrders), ctx, limit)
}

// GetOrderById mocks base method.
func (m *MockOrdersRepository) GetOrderById(order_uid string, ctx context.Context, useCache bool) (*generator.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderById", order_uid, ctx, useCache)
	ret0, _ := ret[0].(*generator.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderById indicates an expected call of GetOrderById.
func (mr *MockOrdersRepositoryMockRecorder) GetOrderById(order_uid, ctx, useCache any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderById", reflect.TypeOf((*MockOrdersRepository)(nil).GetOrderById), order_uid, ctx, useCache)
}

// SaveToDB mocks base method.
func (m *MockOrdersRepository) SaveToDB(orders []*generator.Order, ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToDB", orders, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToDB indicates an expected call of SaveToDB.
func (mr *MockOrdersRepositoryMockRecorder) SaveToDB(orders, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToDB", reflect.TypeOf((*MockOrdersRepository)(nil).SaveToDB), orders, ctx)
}
